### PR TITLE
Updated game2.py

### PR DESCRIPTION
**Pull request by MANUSRAO**

### CODE REVIEW

**Review by Prajwalprakash3722 — COMMENTED** [review]
Instead of writing .lower() for every if condition, it is easier to change the capitalization of every Rock, Paper, Scissors in the whole code and add .lower() to the input()

**Comment by Prajwalprakash3722** [comment]
There are conflicts between your main branch and my main branch, please review the changes and commit the files again

**Comment by Prajwalprakash3722** [comment]
please format the files using black, if you don't have black then install it by `pip install black` then to format run the file by `black filename.py`

**Comment by MANUSRAO** [comment]
> Instead of writing .lower() for every if condition, it is easier to change the capitalization of every Rock, Paper, Scissors in the whole code and add .lower() to the input()
Oh that's correct my bad!! I will change it right now

**Comment by MANUSRAO** [comment]
@Prajwalprakash3722  Please check if indentation is correct now and close the issue

**Pull request merged**
